import { Offer } from "../types";

const offers = [
    {
        id: "1",
        code: "NEWUSER50",
        title: "50% OFF on First Order",
        description: "Get 50% off up to ₹150 on your first order",
        discountPercentage: 50,
        validTill: "Valid till tonight 10 PM",
        terms: "Min order ₹200",
        tag: "New Users",
        color: "bg-blue-50",
        borderColor: "border-blue-200",
        textColor: "text-blue-600",
        foodItems: [],
        applied: false,
        appliedAt: "",
        expiresAt: "2023-12-31T22:00:00Z",
        maxDiscount: 150,
        minOrderAmount: 200
    },
    {
        id: "2",
        code: "WEEKEND40",
        title: "Weekend Special 40% OFF",
        description: "40% off on all orders above ₹500",
        discountPercentage: 40,
        validTill: "Valid today",
        terms: "Max discount ₹200",
        tag: "Weekend",
        color: "bg-orange-50",
        borderColor: "border-orange-200",
        textColor: "text-orange-600",
        foodItems: [],
        applied: false,
        appliedAt: "",
        expiresAt: "2023-12-31T23:59:59Z",
        maxDiscount: 200,
        minOrderAmount: 500
    },
    {
        id: "3",
        code: "BURGER30",
        title: "30% OFF on Burgers",
        description: "Get flat 30% off on all burgers",
        discountPercentage: 30,
        validTill: "Valid for next 2 hours",
        terms: "No minimum order",
        tag: "Category Special",
        color: "bg-green-50",
        borderColor: "border-green-200",
        textColor: "text-green-600",
        foodItems: [],
        applied: false,
        appliedAt: "",
        expiresAt: "2023-12-31T23:59:59Z",
        maxDiscount: 100,
        minOrderAmount: 0
    },
    {
        id: "4",
        code: "FREEDEL",
        title: "Free Delivery",
        description: "Free delivery on your next 3 orders",
        discountPercentage: 0,
        validTill: "Valid for 24 hours",
        terms: "Min order ₹300",
        tag: "Limited Time",
        color: "bg-purple-50",
        borderColor: "border-purple-200",
        textColor: "text-purple-600",
        foodItems: [],
        applied: false,
        appliedAt: "",
        expiresAt: "2023-12-31T23:59:59Z",
        maxDiscount: 0,
        minOrderAmount: 300
    },
    {
        id: "5",
        code: "BULKORDER15",
        title: "Bulk Order Discount",
        description: "Perfect for office lunches or family gatherings. Order 5 or more meals and save big!",
        discountPercentage: 15,
        validTill: "Limited time offer",
        terms: "5 meals minimum",
        tag: "Most Popular",
        color: "bg-yellow-50",
        borderColor: "border-yellow-200",
        textColor: "text-yellow-600",
        foodItems: [],
        applied: false,
        appliedAt: "",
        expiresAt: "2023-12-31T23:59:59Z",
        maxDiscount: 300,
        minOrderAmount: 1000
    },
    {
        id: "monthly-meal",
        code: "MONTHLY20",
        title: "Monthly Meal Plan",
        description: "Curated meals delivered to your doorstep every day. Pause or cancel anytime.",
        discountPercentage: 20,
        validTill: "Monthly subscription",
        terms: "Starts at $199/month",
        tag: "Best Value",
        color: "bg-blue-50",
        borderColor: "border-blue-200",
        textColor: "text-blue-600",
        foodItems: [],
        applied: false,
        appliedAt: "",
        expiresAt: "2023-12-31T23:59:59Z",
        maxDiscount: 500,
        minOrderAmount: 199
    },
    {
        id: "birthday-special",
        code: "BIRTHDAY40",
        title: "Birthday Special",
        description: "Make your celebration extra special with our curated party platters and desserts.",
        discountPercentage: 40,
        validTill: "7 days validity",
        terms: "Order 2hrs in advance",
        tag: "Maximum Discount",
        color: "bg-pink-50",
        borderColor: "border-pink-200",
        textColor: "text-pink-600",
        foodItems: [],
        applied: false,
        appliedAt: "",
        expiresAt: "2023-12-31T23:59:59Z",
        maxDiscount: 400,
        minOrderAmount: 500
    },
    {
        id: "8",
        code: "FREEMEAL",
        title: "Daily Free Meal",
        description: "Join our elite membership for exclusive perks, early access, and special discounts.",
        discountPercentage: 100,
        validTill: "Annual membership",
        terms: "Priority service",
        tag: "New",
        color: "bg-green-50",
        borderColor: "border-green-200",
        textColor: "text-green-600",
        foodItems: [],
        applied: false,
        appliedAt: "",
        expiresAt: "2023-12-31T23:59:59Z",
        maxDiscount: 1000,
        minOrderAmount: 0
    }
] as Offer[];

export default offers;