import { User } from "../types";

const users: User[] = [
    {
        id: "user-001",
        email: "bibhu.sahoo@example.com",
        name: "Bibhu Prasad Sahoo",
        phone: "+917735605546",
        addresses: [
            {
                id: "addr-001",
                name: "Bibhu Prasad Sahoo",
                phoneNumber: "+917735605546",
                houseNumber: "Tetra Boys Hostel",
                street: "Tangi",
                landmark: "Near DRIEMS",
                city: "Cuttack",
                district: "Cuttack",
                state: "Odisha",
                pincode: "754022",
                isDefault: true,
                userId: "user-001"
            },
            {
                id: "addr-002",
                name: "Bibhu Prasad Sahoo",
                phoneNumber: "+917735605546",
                houseNumber: "C-61",
                street: "Tangi",
                landmark: "Near Tangi CHC",
                city: "Cuttack",
                district: "Cuttack",
                state: "Odisha",
                pincode: "754022",
                isDefault: false,
                userId: "user-001"
            },
        ],
        orders: [
            {
                id: "order-001",
                userId: 'user-001',
                items: [
                    {
                        id: "cart-001",
                        type: 'regular',
                        foodItem: {
                            id: "food-001",
                            name: "Margherita Pizza",
                            description: "Classic Italian pizza with fresh mozzarella and basil",
                            price: 12.99,
                            image: "https://images.unsplash.com/photo-1604908177351-966b1f4b9271",
                            categoryId: "main-course",
                            category: "Main Course",
                            rating: 4.5,
                            calories: 250,
                            ingredients: ["Dough", "Tomato Sauce", "Mozzarella", "Basil"],
                            dietaryType: "veg",
                            images: ["https://images.unsplash.com/photo-1604908177351-966b1f4b9271"],
                        },
                        quantity: 2,
                    },
                ],
                total: 25.98,
                status: "delivered",
                createdAt: "2024-08-01T12:00:00Z",
            },
        ],
        reviews: [
            {
                id: "review-001",
                userId: "user-001",
                userName: "Bibhu Prasad Sahoo",
                foodItemId: "food-001",
                rating: 5,
                comment: "Amazing pizza! Will order again.",
                createdAt: "2024-08-02T15:30:00Z",
            },
        ],
        notifications: [
            {
                id: "notif-001",
                title: "Order Delivered",
                message: "Your order has been successfully delivered!",
                timestamp: "2024-08-01T15:00:00Z",
                isRead: false,
                type: "order",
            },
        ],
        cart: [],
        offers: [],
        wishlist: [],
        recentlyViewedItems: [],
    },
    {
        id: "user-002",
        email: "jane.smith@example.com",
        name: "Jane Smith",
        phone: "+9876543210",
        addresses: [
            {
                id: "addr-002",
                name: "Jane Smith",
                phoneNumber: "+9876543210",
                houseNumber: "24A",
                street: "Baker Street",
                landmark: "Near Museum",
                city: "London",
                district: "Central",
                state: "England",
                pincode: "SW1A 1AA",
                isDefault: true,
                userId: "user-002",
            },
        ],
        orders: [
            {
                id: "order-002",
                userId: 'user-002',
                items: [
                    {
                        id: "cart-002",
                        type: 'regular',
                        foodItem: {
                            id: "food-002",
                            name: "Sushi Platter",
                            description: "Assorted fresh sushi with wasabi and soy sauce",
                            price: 18.99,
                            image: "https://images.unsplash.com/photo-1601315325926-c1465cd42d7f",
                            categoryId: "japanese",
                            category: "Japanese",
                            rating: 4.8,
                            calories: 320,
                            ingredients: ["Rice", "Fish", "Seaweed", "Soy Sauce"],
                            dietaryType: "non-veg",
                            images: ["https://images.unsplash.com/photo-1601315325926-c1465cd42d7f"],
                        },
                        quantity: 1,
                    },
                ],
                total: 18.99,
                status: "preparing",
                createdAt: "2024-08-02T10:00:00Z",
            },
        ],
        reviews: [],
        notifications: [
            {
                id: "notif-002",
                title: "Order Update",
                message: "Your order is being prepared!",
                timestamp: "2024-08-02T11:00:00Z",
                isRead: false,
                type: "order",
            },
        ],
        cart: [
            {
                id: "cart-003",
                type: 'regular',
                foodItem: {
                    id: "food-003",
                    name: "Caesar Salad",
                    description: "Fresh romaine lettuce, parmesan, croutons, and Caesar dressing",
                    price: 9.99,
                    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
                    categoryId: "salads",
                    category: "Salads",
                    rating: 4.3,
                    calories: 180,
                    ingredients: ["Lettuce", "Parmesan", "Croutons", "Caesar Dressing"],
                    dietaryType: "veg",
                    images: ["https://images.unsplash.com/photo-1546069901-ba9599a7e63c"],
                },
                quantity: 1,
            },
        ],
        offers: [],
        wishlist: [],
        recentlyViewedItems: [],
    },
];

export default users;
